add_newline = true
format = """\
  $directory\
  $python\
  $nodejs\
  $terraform\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $fill\
  $kubernetes\
  $aws\
  $cmd_duration\
  $line_break\
  $character\
  """

command_timeout = 1000

[aws]
format = '[$symbol$profile(\($region\))]($style) '
disabled = false
symbol = "🅰 "

[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"
us-east-2 = "oh"
us-west-1 = "ca"
us-west-2 = "or"

[fill]
symbol = " "

[cmd_duration]
disabled = false
min_time = 500
format = "took [$duration](bold yellow)"

[terraform]
format = "[$version$workspace]($style) "
disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style))'
modified = "*"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bright-black"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 4
format = "[$path]($style)[$lock_symbol]($lock_style) "

[python]
format = '[${symbol}${pyenv_prefix}${version}(\($virtualenv\))]($style) '
style = "green"
symbol = ""

[username]
style_user = "dimmed blue"
show_always = false

[kubernetes]
format = '[\[$context[\($namespace\)](bold purple)\]]($style) '
style = "cyan"
disabled = false

[time]
disabled = true
